module.exports = {
  apps: [
    {
      name: 'cca-watch',
      script: 'cca-collector.ts',
      args: 'watch',
      interpreter: 'node',
      interpreter_args: '--import tsx/esm',
      autorestart: true,
      max_memory_restart: '300M',
      restart_delay: 5000,
      out_file: 'logs/watch-out.log',
      error_file: 'logs/watch-err.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'cca-bot',
      script: 'bot-server.ts',
      interpreter: 'node',
      interpreter_args: '--import tsx/esm',
      autorestart: true,
      max_memory_restart: '300M',
      restart_delay: 5000,
      out_file: 'logs/bot-out.log',
      error_file: 'logs/bot-err.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'cca-intent',
      script: 'intent-radar.ts',
      interpreter: 'node',
      interpreter_args: '--import tsx/esm',
      autorestart: true,
      max_memory_restart: '300M',
      restart_delay: 5000,
      out_file: 'logs/intent-out.log',
      error_file: 'logs/intent-err.log',
      merge_logs: true,
      time: true,
    },
  ],
}
